### ISSUE TITLE
📑 Add more examples

### ISSUE THREAD

**Issue by LyubomirT** [LyubomirT/lesp#2]
Personally, I think that adding more examples will improve the ease of use of LESP by explaining how to use the project better and in more detail.

**Hint:**

- GUI options could be a very nice addition
- Simple examples are good, but we shouldn't overuse these
- In total, at least 5 examples will be fine. Not more than 8 though.

**Comment by adrienneli104** [comment]
I was wondering if I could work on this issue! Do you have any examples in mind you'd like to see?

**Comment by Halzorg** [comment]
I would like to work on this issue, could you please assign it to me?

**Comment by LyubomirT** [comment]
> I was wondering if I could work on this issue! Do you have any examples in mind you'd like to see?

Thank you for your interest in contributing! I think some examples that combine some of the features in a single app or have a GUI would look good. Currently there is already a `tkinter` sample, but something like Flask would not be useless.

You can simply put the source code into a file or two, it shouldn't be overcomplicated.

**Comment by LyubomirT** [comment]
> I would like to work on this issue, could you please assign it to me?

Hello! Since there are two people who would like to work on this issue, I'll assign both of you. Thank you for your interest in contributing to LESP!

**Comment by LyubomirT** [comment]
Implemented by @Halzorg!
